vittorioromeo/SSVOpenHexagon

build-repository-rel.sh, old_scripts/build-repository-oh.sh
I found cmake doesn't parse -D argument well.
I guess "" at cmake command escape space character.
Original result CMakeCache.txt :
//Path to a program.
CMAKE_AR:FILEPATH=/usr/bin/ar
//Choose the type of build, options are: None(CMAKE_CXX_FLAGS or
// CMAKE_C_FLAGS used) Debug Release RelWithDebInfo MinSizeRel.
CMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INCLUDE_PATH=/home/pusnow/Develop/SSVOpenHexagon/extlibs/SSVUtils:/home/pusnow/Develop/SSVOpenHexagon/extlibs/SSVUtils/include:/home/pusnow/Develop/SSVOpenHexagon/extlibs/SSVMenuSystem:/home/pusnow/Develop/SSVOpenHexagon/extlibs/SSVMenuSystem/include:/home/pusnow/Develop/SSVOpenHexagon/extlibs/SSVEntitySystem:/home/pusnow/Develop/SSVOpenHexagon/extlibs/SSVEntitySystem/include:/home/pusnow/Develop/SSVOpenHexagon/extlibs/SSVLuaWrapper:/home/pusnow …
=> cmake args fix

cmake/modules/FindLUA.cmake
OpenBSD installs the headers under /usr/local/include/lua-5.3. This change is enough to pick it up.
=> Additional search path for lua.

src/SSVOpenHexagon/Core/HGScripting.cpp
This is a feature pack developers have wanted for a long time, now you can track the inputs of the mouse alongside the keyboard in Lua code, removing "[Keyboard Required]" from (most) levels altogether.
=> Added Lua Mouse Support (u_isButtonPressed)

src/SSVOpenHexagon/Core/HGGraphics.cpp
This one line of code fixes the bug where the message text doesn't scale accordingly to the resolution of the window, leading to the text being huge on smaller resolution screens, and being smaller on higher resolutions.
=> Fix Scaling Bug On Message Text

include/SSVOpenHexagon/Core/HexagonGame.hpp, include/SSVOpenHexagon/Data/MusicData.hpp, src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp
This is an addition of several new Lua functions into the Lua library. A lot of these functions were based off event functions that were exclusive to JSON in 1.92, which means that anybody who wants to port their packs from 1.92 can do this more easily if their levels were very reliant on events. 
I didn't do menu, because that can be substituted for "kill" and clearTimeline has been completely replaced with clearWalls, which provides much more useful functionality of clearing out all of the walls in a current level (because clearTimeline was pointless). 
Sorry for the merge issues. This probably has to do with the fact I have to add all the new Lua functions to the whitelist so the debugger doesn't make pointless errors.
=> Make functions previously exclusive in JSON events into Lua functions

_RELEASE/Packs/cube/Styles/apeirogon.json, _RELEASE/Packs/cube/Styles/babysteps.json, _RELEASE/Packs/cube/Styles/commando.json, _RELEASE/Packs/cube/Styles/euclideanpc.json, _RELEASE/Packs/cube/Styles/flatteringshape.json, _RELEASE/Packs/cube/Styles/goldenratio.json, _RELEASE/Packs/cube/Styles/labyrinth.json, _RELEASE/Packs/cube/Styles/pi.json, _RELEASE/Packs/cube/Styles/pointless.json, _RELEASE/Packs/cube/Styles/seconddimension.json, _RELEASE/Packs/hypercube/Styles/acceleradiant.json, _RELEASE/Packs/hypercube/Styles/centrifugal.json, _RELEASE/Packs/hypercube/Styles/disc-o.json, _RELEASE/Packs/hypercube/Styles/evotutorial.json, _RELEASE/Packs/hypercube/Styles/g-force.json, _RELEASE/Packs/hypercube/Styles/incongruence.json, _RELEASE/Packs/hypercube/Styles/massacre.json, _RELEASE/Packs/hypercube/Styles/polyhedrug.json, _RELEASE/Packs/hypercube/Styles/reppaws.json, _RELEASE/Packs/hypercube/Styles/slither.json, include/SSVOpenHexagon/Data/CapColor.hpp, include/SSVOpenHexagon/Data/ColorData.hpp, include/SSVOpenHexagon/Data/StyleData.hpp, src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Data/CapColor.cpp, src/SSVOpenHexagon/Data/StyleData.cpp
This expands upon the Cap Color code that was originally introduced to now accept color data, such as how it is done when configuring the main color or the colors for your background panels. 
1.92 style colorization is known as "legacy" and can be switched on and off. Also includes one quick fix of C++ code and also updates all of the level styles to have cap color configurations that seem to be most ideal for them.
=> Expand Cap Color to be more customizable

_RELEASE/Packs/hypercube/Scripts/nextpatterns.lua, src/SSVOpenHexagon/Core/HGScripting.cpp
This is a quick fix to impossible outcomes in Acceleradiant by reprogramming wallAcc to adjust the acceleration of the walls based on the difficulty multiplier. This does not heavily affect any other levels as far as I know and no difference is made when played on normal difficulty.
Also made a slight tweak to some of the next patterns to adjust to this new code (especially acceleradiant).
=> Fix wallAcc with new caps

src/SSVOpenHexagon/Core/HexagonGame.cpp
Since optional functions exist, I thought that it would be a great idea if I decide to add one of my own. I call this one onDeath(), which is run when the player dies. They have to ACTUALLY die to get this to run, so if they turn on invincibility mode this function will not run.
It's a simple addition, but oh the many possibilities that can open up with just this one function.
=> Add new optional Lua function onDeath

_RELEASE/Packs/cube/Scripts/Levels/goldenratio.lua, src/SSVOpenHexagon/Core/HexagonGame.cpp
Fixes #191.
As a result, I set Golden Ratios beginning speed equal to 0. Now it is how it was intended to be.
=> Fix zero rotation issue

_RELEASE/Packs/cube/Scripts/alternativepatterns.lua, _RELEASE/Packs/cube/Scripts/common.lua, _RELEASE/Packs/cube/Scripts/commonpatterns.lua, _RELEASE/Packs/experimental/Scripts/alternativepatterns.lua, _RELEASE/Packs/experimental/Scripts/common.lua, _RELEASE/Packs/experimental/Scripts/commonpatterns.lua, _RELEASE/Packs/experimental/Scripts/evolutionpatterns.lua, _RELEASE/Packs/experimental/Scripts/nextpatterns.lua, _RELEASE/Packs/hypercube/Scripts/alternativepatterns.lua, _RELEASE/Packs/hypercube/Scripts/common.lua, _RELEASE/Packs/hypercube/Scripts/commonpatterns.lua, _RELEASE/Packs/hypercube/Scripts/evolutionpatterns.lua, _RELEASE/Packs/hypercube/Scripts/nextpatterns.lua
This was a bug that has been picked up by one of the community members last night, where he noticed that mirror spirals were not randomizing in their direction, but singular spirals did. It turns out that this was happening because "loopDir", the variable that is used to assign the direction of where the spiral goes, was constantly being overwritten by cWallEx, a function called in the spiral functions to create the walls. This pull request fixes this issue by renaming the loopDir variable in cWallEx to something else, so it doesn't overwrite the value of the loopDir in spiral patterns.
I also made it so pSpiral uses cWallEx now instead of just cWall and I also made a ton of variables in common patterns local, to ensure scope safety of a lot of the variables.
=> Fix spirals not randomizing direction in common patterns

_RELEASE/Packs/experimental/Levels/3D_required.json, _RELEASE/Packs/experimental/Scripts/Levels/3D_required.lua, include/SSVOpenHexagon/Core/HGStatus.hpp, include/SSVOpenHexagon/Core/HexagonGame.hpp, include/SSVOpenHexagon/Data/LevelData.hpp, src/SSVOpenHexagon/Core/HGGraphics.cpp, src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Core/HGUpdate.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Global/Config.cpp
Fixes #200 
Does pretty much it asks. Use l_set3dRequired(boolean) and l_get3dRequired. 
I also:
- Made the "Score Invalidated" display parameterized, which means that you can now add many more reasons to invalidate a score. 
- Fixed a major oversight in the game design and I heavily increased the standards for local scores to have the same standards online scores have. I have no idea why it was the case that the standards were so low for local scores, but now you can't just turn off official mode and get away with it.
- Added an experimental level to try out the 3D required yourself.
=> Add 3D Required as a toggleable requirement for score eligibility on 3D-reliant levels

README.md
This PR makes slight updates to the README, as this was recently built on Linux Mint 20 successfully thanks to Alpha's new instructions. 
One of these changes adds a tip of how to substitute OpenGL, in case the distribution can't find the OpenGL library. Also, I added which Linux distributions were tested for additional information.
=> Make slight updates to README

.github/workflows/ci.yml
This PR adds automatic CI builds for Linux. Every time a push or pull request is made, GitHub Actions will spin up an Ubuntu container that automatically checks out the repository, downloads dependencies, builds the game, and uploads the result. Anyone with a GitHub account can go to the Actions page, click the latest run, and download said build.
These CI builds serve two purposes: (1) to check that changes made to the codebase will compile correctly, and (2) to provide convenient builds so players don't have to clone and compile the game for themselves. (However, it's still a bit annoying, because you have to make a GitHub account and log in, but it's better than nothing.)
I would have liked to add CI builds for Windows and macOS, but every approach I tried for either of those two …
=> Add CI builds for Linux

_RELEASE/Packs/experimental/Levels/negative_pulse.json, _RELEASE/Packs/experimental/Scripts/Levels/negative_pulse.lua, _RELEASE/Packs/experimental/Styles/negative_pulse.json, include/SSVOpenHexagon/Data/ColorData.hpp, src/SSVOpenHexagon/Data/CapColor.cpp, src/SSVOpenHexagon/Data/ColorData.cpp
Closes #241.
Had to make my own struct and all that to accomplish this. I wouldn't have been able to do this without a bit of help from @SuperV1234  and @MultHub, because I was struggling to figure out how the JSON Parser worked when parsing arrays. 
Hopefully people can now make all new types of styles with this restriction removed.
=> Allow styles to support negative values for the `"Pulse" field

.github/workflows/ci.yml
Now, every time the CI builds the game, tests will be run afterwards. I put the tests last so the tests failing won't mean artifacts won't be uploaded.
Closes #202.
=> Add unit tests to CI

include/SSVOpenHexagon/Core/HexagonGame.hpp, src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp
Closes #237 and fixes #244 
Things that will be destroyed:
- The entire "os" library
- The entire "io" library
- The "math.randomseed" function
This is an URGENT pull request that is needed, because this will fix critical security issues of Open Hexagon. This stops bad faithed people from being able to use Lua code to write malware and be able to harm computers of Open Hexagon players. 
If you can, please try and push this fix into the main branch of Open Hexagon for Steam, because this is something super serious and we want to apply this fix quickly before someone writes malware for the game.
=> [URGENT] Destroy Lua Libraries and Functions That Can Be Used Maliciously

README.md
I have not been following this project for a while, and hot damn! So many changes have been made! I saw that there's now a build script and the Arch build instructions didn't reflect that, so I rewrote that part. Tested it on my machine and builds flawlessly on Manjaro 20.0.3.
Also, congrats on the Steam launch! I might buy it when I can to support this project.
=> Update build instructions on Arch

include/SSVOpenHexagon/Core/HexagonGame.hpp, src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp
Closes #245.
Instead of making improvements on u_playSound I decided to make a separate function called u_playPackSound in case people want to still be able to play programmer assets.
=> Add u_playPackSound to simplify playing sounds

src/SSVOpenHexagon/Core/MenuGame.cpp
Turns out that adding silent messages was not added to the menu Lua, which means that the menu would error whenever the function was present. This is just a very simple addition that fixes this bug.
=> Add silent message function to menu Lua

src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp
I took a look at ``t_eval``, which is one of the more recent functions that have been added, and it's surprised me that you can run Lua code using a function. So what I decided to do was to create the _event timeline_ equivalent of ``t_eval``. And I've remade my Fusion level to work off the ``e_eval`` function, and it works. I don't have to use ``onUpdate`` anymore to rely on carrying out events, as I can now define them all in ``onLoad``. 
**A lot of people** want 1.92 events to be in 2.0, and I think this is the closest that we'll ever get to having Events in 2.0 Open Hexagon. After this, I would say we've brought back events to 2.0. I don't care for the super bitter people who want JSON events back, but those aren't coming back. This is the best you're going to get when it comes to …
=> Add e_eval to Lua, the closest we'll get to 1.92 events.

_RELEASE/Packs/experimental/Levels/collision_test.json, _RELEASE/Packs/experimental/Scripts/Levels/collision_test.lua, _RELEASE/Packs/experimental/Styles/wall_ref.json
Am doing this at the request of @SuperV1234. This just adds a level where it specializes in testing the collision system for ordinary walls (side collisions), to make sure that they work properly. (Currently the no overlap is having problems).
=> Add Collision Test Level for Side Collision Testing

_RELEASE/Packs/experimental/Styles/negative_pulse.json, include/SSVOpenHexagon/Core/HexagonGame.hpp, include/SSVOpenHexagon/Core/MenuGame.hpp, include/SSVOpenHexagon/Data/StyleData.hpp, src/SSVOpenHexagon/Components/CPlayer.cpp, src/SSVOpenHexagon/Core/HGGraphics.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Data/StyleData.cpp
Fixes #259 and partially solves #260. The only thing about 260 that isn't solved is the swap color. I took a look at how color works for swapping and the logic works much differently than your traditional color logic. It will take some time for me to think of how I'll be able to get swap color to be customizable (while at the same time, making sure that players can identify that a swap color means that they can swap, so pack devs can't just be dicks). 
In the meantime, I've decided to make the improvements to the styles so dynamic colors should no longer get stuck on pink/magenta when they surpass 360, along with being able to customize player and text by giving them their own color properties. They can now function as their own ColorDatas that pack developers can tweak and modify. …
=> Improve Styles by Patching Hue Clamping and Adding Player Color and Text Color Overrides

include/SSVOpenHexagon/Data/LevelData.hpp, src/SSVOpenHexagon/Core/HGGraphics.cpp
I consider this more of a bug fix than a feature. Previously setting camera shake wouldn't accept float values. Now it can. Pretty simple fix.
=> Get Camera Shake to accept float values

src/SSVOpenHexagon/Core/MenuGame.cpp
As the title states.
The issue is caused by the fact that the position of the text to be rendered is calculated depending on the width of the longest line.
Although this length has a different value when the longest line is selected because extra the selected pack indicator ">>> " takes more horizontal space than "    ".
To solve the problem, while the string of the pack list is being created the longest line is found and stored, and the horizontal offset of the list is calculates depending on its length.
=> Fix pack list in main menu shifting horizontally when longest named pack is selected

src/SSVOpenHexagon/Core/HGUpdate.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp
I find it quite funny that onLoad runs at level initialization, the same time as when onInit runs, which kind of makes it silly that onInit and onLoad are separate functions when they do the exact same thing.
However, this makes onLoad run when the level is finished loading and the level starts, which I think is what onLoad was intended to do. 
Also by doing this we also fix a few bugs with Lua functions. Setting music by segments and seconds previously didn't work properly with onLoad because the music player is paused while the onLoad function is called; it was because of this that the music would always play at the beginning, no matter what segment or timestamp was given. With this new placement the music starts playing before onLoad is ran, making those functions run properly.
=> onLoad runs when the level starts instead of level initialization

include/SSVOpenHexagon/Core/MenuGame.hpp, include/SSVOpenHexagon/Global/Assets.hpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Core/main.cpp
Brief: add command line parameter -l and a level name to make OH load a level on boot. Mostly meant for level makers who might take advantage of not scrolling trough the menus to start the level they are working on.
https://youtu.be/9iyT4n7QacA
Details:
- add -l followed by the level name to load straight into the level (arguments used in the video are -l seconddimension);
- the level name is sent to the Menu class when MenuGame::Init() is called for the first time and here it is processed to see if there is a loaded level with matching name. In case no level is found an error message is printed to console and the load process is aborted;
- the level load will also abort if there is no local profile created, and the process will stop at the profile creation screen.
Notes:
- I store the …
=> Boot OH into a level with command line argument

include/SSVOpenHexagon/Components/CPlayer.hpp, include/SSVOpenHexagon/Core/HexagonGame.hpp, include/SSVOpenHexagon/Data/LevelData.hpp, src/SSVOpenHexagon/Components/CPlayer.cpp, src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp
Brief:
use l_setPlayerSpeedMult() to apply a multiplier to the player speed. If not used, by default the multiplier is 1.f. l_getPlayerSpeedMult() returns the value.
Details:
- when player is created a reference to the LevelStatus value playerSpeedMult is passed, so that it can be checked upon during the level;
- the multiplier is applied onto the player speed in CPlayer::updateInput().
Extra notes:
removed a few redundant includes.
=> Lua function to edit the player movement speed

include/SSVOpenHexagon/Core/MenuGame.hpp, include/SSVOpenHexagon/Data/LevelData.hpp, include/SSVOpenHexagon/Global/Assets.hpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Global/Assets.cpp
Brief:
press F5 in the main menu to reload the assets of the currently selected level. To be used by pack developers so that they don't have to turn OH off and on to test small changes.
https://youtu.be/DPiZLw8cshQ
Details:
- press F5 in the main menu to reload assets of the level;
- function reload the level data and then music, style, and custom sounds files the level data .json is pointing to;
- error messages are printed in console if the file does not exist;
- files to be reloaded must be in the pack directory subfolders (ex. PackPath/Music/ or PackPath/Style/);
- new music and custom sound files are not reloaded if they have been already cached at boot.
Extra notes:
- removed some redundant includes;
- added soundId to LevelData class;
- slightly reorganized Assets.hpp and …
=> Reload assets of level selected in the main menu

webpage/index.html
This should complete the Workshop Tutorials move to GitHub Wiki. The old tutorial itself should be removed as well but I didn't include that here.
Closes #257
=> Point Workshop Tutorial on website to GitHub Wiki

include/SSVOpenHexagon/Core/HexagonGame.hpp, include/SSVOpenHexagon/Core/Replay.hpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/Replay.cpp, test/Replay.t.cpp
This is a minor shift in the code so that way onUnload is now called after an initial runthrough of the entire Lua file. This is done to help ensure that onUnload is used for the purpose of changing level features after a first playthrough of the level, like intended.
=> Fix onUnload's priority

src/SSVOpenHexagon/Global/Config.cpp
When a new key was assigned to a bind slot already taken by another key, the latter one was not wiped beforehand, causing load/read/save config issues.
This is what happened to the config.json file
```
"t_rotate_ccw" : 
[
[ "kD", "kP" ], // causes issues
[ "kC" ]
],
```
=> Keyboard bind menu item bugfix

_RELEASE/config.json, include/SSVOpenHexagon/Core/BindControl.hpp, include/SSVOpenHexagon/Core/MenuGame.hpp, include/SSVOpenHexagon/Global/Config.hpp, include/SSVOpenHexagon/Global/UtilsJson.hpp, misc/default_config.json, src/SSVOpenHexagon/Core/BindControl.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Global/Config.cpp
- Increased keys per bind cap from 2 to 4;
- allowed assigning a same key to multiple binds;
- fixed an issue that caused OH to crash when the config was saved closing the game (fix in UtilJson.hpp, solution looks cheap and something else might fit better);
- added "t_select" to config.json, and added such bind customization in the menu;
- removed hardcoded keys bind prohibition;
- removed a slew of now useless Config functions;
- limited hardcoded key actions to Enter, Escape, Up, Down, Right, and Left.
=> Bind controls beta testers suggestions

include/SSVOpenHexagon/Core/BindControl.hpp, include/SSVOpenHexagon/Core/HexagonDialogBox.hpp, include/SSVOpenHexagon/Core/MenuGame.hpp, include/SSVOpenHexagon/Global/Config.hpp, src/SSVOpenHexagon/Core/BindControl.cpp, src/SSVOpenHexagon/Core/HexagonDialogBox.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Global/Config.cpp
```
void create(const std::string& output, const int charSize, const float mFrameSize, const int mDrawMode,
const float mXPos = 0.f, const float mYPos = 0.f);
void create(const std::string& output, const int charSize, const float mFrameSize, const int mDrawMode,
const KKey mKeyToClose, const float mXPos = 0.f, const float mYPos = 0.f);
void draw(const Color& txtColor, const Color& backdropColor);
```
- mDrawMode 1 (DBoxDraw::topLeft) will place the box at {xPos, yPos} from the top left corner;
- mDrawMode 2 (DBoxDraw::center) will place the box at {xPos, yPos} from the screen center;
- mDrawMode 3 (DBoxDraw::centerUpperHalf) is a specialized version for the level reload function.
NOTE: xPos positive values shift the box to the right, yPos positive values shift it toward the bottom.
Also: …
=> Increased Dialog Box Customization

include/SSVOpenHexagon/Core/MenuGame.hpp, include/SSVOpenHexagon/Global/Config.hpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Global/Config.cpp
"reset configs to default" in the main options menu resets all configs.
"reset binds to defaults" in the gameplay submenu only resets all the keyboard-mouse-joystick binds.
=> Options menu items to reset configs to defaults

include/SSVOpenHexagon/Core/MenuGame.hpp, include/SSVOpenHexagon/Global/Assets.hpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Global/Assets.cpp, src/SSVOpenHexagon/Global/Config.cpp
As by the title, added a new function to reload all levels in the currently selected pack when F6 is pressed.
Extras:
- modified level reload function to accept new files to match the behavior of the pack reload. Also condensed the whole process in just one function;
- implemented a safer way to agglomerate key binds on boot if there are empty slots in between (also much better looking);
- removed hardcoded left and right. Most people will bind the right and left arrows to left and right actions anyway causing the execution of both the hardcoded action and the customizable one (for ex. causing to move two levels in the level selection menu);
- cleaned up a couple of leftover comments from HexagonGame.cpp.
=> Press F6 to reload the entire selected pack

include/SSVOpenHexagon/Core/Steam.hpp
Before, was causing errors:
```
In file included from /usr/include/c++/10.2.0/unordered_map:42,
from /usr/include/c++/10.2.0/functional:61,
from /opt/SSVOpenHexagon/./include/SSVOpenHexagon/Core/Steam.hpp:10,
from /opt/SSVOpenHexagon/src/SSVOpenHexagon/Core/Steam.cpp:5:
/usr/include/c++/10.2.0/ext/aligned_buffer.h: In instantiation of ‘struct __gnu_cxx::__aligned_buffer<std::__cxx11::basic_string<char> >’:
/usr/include/c++/10.2.0/bits/hashtable_policy.h:233:43:   required from ‘struct std::__detail::_Hash_node_value_base<std::__cxx11::basic_string<char> >’
/usr/include/c++/10.2.0/bits/hashtable_policy.h:264:12:   required from ‘struct std::__detail::_Hash_node<std::__cxx11::basic_string<char>, true>’
/usr/include/c++/10.2.0/bits/hashtable_policy.h:1973:13:   required from ‘struct …
```
=> Include string explicitly so that the type is complete

include/SSVOpenHexagon/Core/MenuGame.hpp, src/SSVOpenHexagon/Core/MenuGame.cpp
- Fixed pack switch still getting stuck in some circumstances I cannot figure out (assignement is now constantly updated instead of being bound to key press/release events);
- Added wrapping to the level description. It would be better if pack makers updated their jsons with newlines to fit the space available as they see fit, but since it is possible some packs may never be updated I enforce a formatting when the level is changed.
It should be noted that I have noticed some weird glitches in the formatted text rendering in certain packs (particularly Babagon). Best I can tell it's due to the editor used to make the jsons since if I retype the description as in the original in my text editors the issue is fixed.
=> Further menu improvements

src/SSVOpenHexagon/Core/Joystick.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Global/Config.cpp
Assigned Focus bind to control the quick switch function when in menu (its in game behavior is unchanged).
Also:
- replaced a #define in Config.cpp with a constexpr;
- added pack change keys to RefreshBinds();
- small tweak in formatLevelDescription().
A new custom bind can be made but that would make the bind customization menu go out of bounds and would require a bigger amount of effort.
=> Customizable Quick Pack Switch key

include/SSVOpenHexagon/Core/HexagonGame.hpp, include/SSVOpenHexagon/Data/LevelData.hpp, src/SSVOpenHexagon/Components/CPlayer.cpp, src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp
This PR introduces 6 new Lua functions that all expand the new **a_** prefix that was introduced.
Two of these functions are dedicated to the pitch of the music
1. **a_syncMusicToDM**: Allows pack developers to override the user's preference of whether the music's pitch is synced with the difficulty multiplier. By default, the value is based on the user's preference.
2. **a_setMusicPitch**: Allows pack developers to manually adjust the pitch of the music playing. Due to SFML limitations, this function does not accept negative values.
The other four are asset overriding functions, which allow pack developers to override some of the default sounds with their own custom ones.
1. **a_overrideBeepSound**: Overrides beep.ogg with a level pack sound to the developer's liking.
2. …
=> Expand the audio prefix (First Expansion)

src/SSVOpenHexagon/Core/MenuGame.cpp
Fixes a couple of issues in the way the level description was formatted when multiple consecutive newlines were written in the .json file.
=> Multiple newlines in description bugfixes

src/SSVOpenHexagon/Components/CPlayer.cpp, src/SSVOpenHexagon/Core/HGUpdate.cpp
Fixes #312
"hue" parameter update has been moved from drawDeathEffect() to update(), fixing the frame dependency.
Furthermore, to make it work CPlayer::update() is now executed even when player is dead, except that when it is dead, after the death effect Ticker and hue have been updated the function is terminated.
From my testing it works as expected when Invincible is on and when it is off.
=> Fixed death effect being FPS dependent

include/SSVOpenHexagon/Core/MenuGame.hpp, src/SSVOpenHexagon/Core/MenuGame.cpp
Recently I noticed how sometimes the game stutters when changing selected level in the menu.
I suspect the culprit is the function initLua() which does a pretty significant amount of work and is called every time the index of the level selection is changed.
I have slightly reworked it to only be called on menu initialization. There seem to be no drawbacks from this new approach.
P.S: I have also renamed a variable with a misleading name and re-added the "DIFFICULTY: " string that had been removed by accident (at least I think, sorry if that was intentional and I could not figure out the reason).
=> Only call initLua() at boot

src/SSVOpenHexagon/Core/MenuGame.cpp
As per title.
A small fix to address wonky behavior in the level selection menu after using the command line level load.
=> Fix glitchy level selection after command line level load

include/SSVOpenHexagon/Core/BindControl.hpp, src/SSVOpenHexagon/Core/BindControl.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp
Added a little menu option to display a message showing all the hardcoded controls.
I originally wanted to show the controls somewhere in the menu themselves but could not find a suitable spot where to place them without causing overlaps or making the screen too busy.
While a bit old school I think this is a simple and elegant solution.
Also, since F1 to F4 are no longer used I have reassigned the currently in use FX keys as shown in the picture.
=> Hardcoded keys reference message

include/SSVOpenHexagon/Core/MenuGame.hpp, src/SSVOpenHexagon/Core/MenuGame.cpp
Also improved the quick switch list scrolling (now it shows one label ahead/behind depending on the height of the labels).
NOTE: the tip can never be covered by a level label thanks to the look-ahead level scrolling system.
=> Favorite levels visual cue

src/SSVOpenHexagon/Core/MenuGame.cpp
Changing level in the favorite levels submenu was not updating the pack id, and therefore the level description always defaulted to the pack at index 0.
=> Fixed pack description in favorites

src/SSVOpenHexagon/Components/CPlayer.cpp
The fix: in CPlayer::push() I was reusing lastAngle and lastPos to store the position to be tested for overlap.
Problem is, to then figure put where the player should have been repositioned we need to use the actual position in the previous frame, not the test position i stored in the variables a few lines before.
This was an issue on levels with an outrageous amount of sides (more than 50) where pinpoint accuracy was essential.
Instead of reusing lastPos I added a dedicated variable in the function (testPos) to store the position to be tested after the movement compensation.
=> fix collision on levels with a really high amount of sides

include/SSVOpenHexagon/Core/BindControl.hpp, include/SSVOpenHexagon/Core/MenuGame.hpp, src/SSVOpenHexagon/Core/BindControl.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp
The favorites menu scroll looked janky when there were more level labels than they could fit on screen.
This solves the issue.
=> Fix favorites menu scroll

buildlx/cmake_gcc.sh, include/SSVOpenHexagon/Components/CPlayer.hpp, include/SSVOpenHexagon/Core/HexagonGame.hpp, include/SSVOpenHexagon/Global/Assets.hpp, include/SSVOpenHexagon/Global/Config.hpp, include/SSVOpenHexagon/Utils/LuaMetadataProxy.hpp, include/SSVOpenHexagon/Utils/LuaWrapper.hpp, include/SSVOpenHexagon/Utils/Utils.hpp, src/SSVOpenHexagon/Components/CPlayer.cpp, src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Core/HGUpdate.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Global/Config.cpp
- Minor fixes and optimizations
- Added a few milliseconds of ignoring input after death to avoid accidental restarts
- Added a new built-in Lua function, 'onSwap', called when the player successfully swaps
- Fixed 't_eval' crashing on Lua error
- Added 's_getMainColor' which returns a RGBA tuple of the current main color
=> Minor fixes/changes for 2.0.4

src/SSVOpenHexagon/Core/MenuGame.cpp
As per title, now focus presses only effect the menu when in Level Selection.
=> Fix focus resetting background animation in main menu

build/copyArtifacts.bash
This is a bash script that was designed to copy the build artifacts and supply all the necessary DLLs to _RELEASE for the game to run properly, along with the executables themselves.
The bash script asks for the user's `msys64` folder, as the msys system has some DLLs that are needed to be copied.
=> Add bash script to copy build artifacts

_RELEASE/Packs/experimental/Levels/wall_color_test.json, _RELEASE/Packs/experimental/Styles/construct.json, include/SSVOpenHexagon/Core/HexagonGame.hpp, include/SSVOpenHexagon/Data/StyleData.hpp, src/SSVOpenHexagon/Core/HGGraphics.cpp, src/SSVOpenHexagon/Data/StyleData.cpp
Another little pull request that I want to add to the game. This one adds a wall color override, which I should've done back in 2.0.3. I've even made a nice little experimental level with a style that I created using the wall color override, and it shows how you can make some nice stuff. I think it's nice you can have some wall color customization without the need to use custom walls.
I'm coming back to source code development with small little pull requests like these before I have to start working on my bigger changes.
=> Add Wall Color Override to style JSONs

include/SSVOpenHexagon/Core/HexagonGame.hpp, include/SSVOpenHexagon/Data/StyleData.hpp, src/SSVOpenHexagon/Core/HGGraphics.cpp, src/SSVOpenHexagon/Core/HexagonGame.cpp, src/SSVOpenHexagon/Core/MenuGame.cpp, src/SSVOpenHexagon/Data/StyleData.cpp
I know that a lot of people don't pay attention to Black And White mode, but I wanted to enable it so I could have some pictures for some artwork, and noticed how Black And White hasn't adjusted to fit some of the new style changes that have been introduced. This pull request fixes those bugs and also tries its best to provide a convincing Black And White look to the level selection menu as well.
Still, a bug fix is a bug fix.
=> Fix Black and White showing color in level / menu

build/copyArtifacts.bash
sfml-build dlls are now on 3, up from 2, so the current copyArtifacts.bash doesn't locate them correctly and will fail to copy them. This fixes that
=> Copy artifacts update

_RELEASE/Packs/base/Scripts/utils.lua
The original shuffle function was a wrong implementation of the Fisher-Yates shuffle.
=> Fix the shuffle function

include/SSVOpenHexagon/Core/MenuGame.hpp, src/SSVOpenHexagon/Core/MenuGame.cpp
Opened OH to check on the last update and noticed a bug in the level selection menu, as shown in the video.
(After the stretch, at the bottom of the screen there should be the selected level, which is the last one of the last pack)
https://youtu.be/Bz_ul7hOxa0
I haved fixed it and did some testing, everything seems to behave as it should.
=> Fix faulty last pack menu stretch

_RELEASE/Packs/base/Scripts/utils.lua, _RELEASE/Packs/experimental/Levels/text_shader.json, _RELEASE/Packs/experimental/Scripts/Levels/text_shader.lua, _RELEASE/Packs/experimental/Shaders/text.frag, include/SSVOpenHexagon/Core/HGStatus.hpp, include/SSVOpenHexagon/Core/HexagonGame.hpp, src/SSVOpenHexagon/Core/HGGraphics.cpp
This pr adds the ability to modify the text color with fragment shaders. However it is a bit more unintuitive than the other RenderStages. So a shader that sets the outline to red and the text to green could look like this:
```glsl
#version 130
uniform vec4 color0;
uniform sampler2D font;
void main()
{
vec4 color = gl_Color.rgb == color0.rgb ? vec4(1,0,0,1) : vec4(0,1,0,1);
gl_FragColor = color * texture(font, gl_TexCoord[0].xy);
}
```
with `color0` being `s_getColor(0)` in order to set an outline color.
=> Add text shaders

src/SSVOpenHexagon/Core/HexagonGame.cpp
I'm not sure if I should put all changes for parity in one big pull request rather than a lot of small ones now, but here is another one either way. This change is very specific to allow the function to run after timeline, levelStatus and a few other things have already been reset, while the lua environment has not. This way levels can actually access their lua variables when unloading, the old onUnload is kept for backwards compatability as well as the ability to tell if an attempt is a first attempt. This is also a very important change to make the level_change event that I implemented in my converter function properly since it needs to restart in the level it changed (There is a level that heavily relies on this mechanic.).
=> Add onPreUnload core function

src/SSVOpenHexagon/Core/HGGraphics.cpp
This is another small one. It just gives the onRenderStage core function frametime as second parameter which allows for more accurately timed shader effects, since `l_getLevelTime()` only updates 240 times per second.
=> add frametime parameter to onRenderStage

include/SSVOpenHexagon/Core/HexagonGame.hpp, src/SSVOpenHexagon/Core/HexagonGame.cpp
This PR fixes replays saving twice when dying and then exiting to menu and replays not saving when restarting without dying.
This way counting replay files will actually give the amount of attempts in a level.
Should fix #371.
=> Fix replays not saving or saving twice

include/SSVOpenHexagon/Core/HexagonGame.hpp, src/SSVOpenHexagon/Core/HGScripting.cpp, src/SSVOpenHexagon/Core/HGUpdate.cpp, src/SSVOpenHexagon/Core/LuaScripting.cpp
This one is mainly for a few levels in 1.92 that use these effects to an extreme extent, for those I need to be able to set the pulse values more than 240 times per second.
=> Make manual (Beat)Pulse control update immediately

src/SSVOpenHexagon/Core/HexagonGame.cpp
A really small change that makes it so replays are now saved under `Replays/levelId/difficultyMult/`, rather than just `/Replays`.
Example: A replay for Incongruence at 0.5x would be saved under `Replays\ohvrvanilla_vittorio_romeo_hypercube_1_incongruence\0.5x\replayName.ohr.z`
Tested and confirmed functional, and a quick code read indicates that it should not affect uploading to leaderboards (I seem to be unable to actually test this locally however, I assume logging in to the server is disabled via the github build)
=> Organize replays into folders

src/SSVOpenHexagon/Core/HGUpdate.cpp
This PR fixes the bug where a message appears at the wrong position at first and is positioned correctly in the next tick.
This bug is especially noticable in levels that create new messages very frequently.
=> Fix text appearing in wrong position for a tick

include/SSVOpenHexagon/Core/HexagonGame.hpp, src/SSVOpenHexagon/Core/HexagonGame.cpp
Some testing in wine and on windows by other people has revealed that windows doesn't like certain characters in file paths. However some 1.92 packs use these in their name/id, so I need this to be fixed without changing that, which is what this PR does. It just replaces the invalid characters with spaces now.
=> Fix replay path issues on windows

src/SSVOpenHexagon/Core/LuaScripting.cpp
For some reason the game looked for dependency shaders in the scripts folder, this should be fixed with this PR.
=> fix dependency shaders
